import asyncio
from src.prompts import generate_followup
from src.utils import ModelType
from src.ai import get_ai_responses

async def followups(user_query_messages):
    """
    Generate follow-up questions for the user query messages.
    The input is a list contains dictionaries with the role and content of the message.
    The output is a list of follow-up questions generated by the REASONING model.
    For example user_query_messages could be:
    user_query_messages =
    [
        {"role": "user", "content": "What is the capital of France?"}
    ]   
    
    """ 
    messages = generate_followup + user_query_messages
    responses = await get_ai_responses( messages= messages, model= ModelType.REASONING)
    return responses
    